### PR TITLE
Update lodash version to 3

### PR DESCRIPTION
**Pull request by mpolci**
I upgraded lodash dependency because lodash 2 is deprecated and not mantained.

### CODE REVIEW

**Comment by corybill** [comment]
Do you run the tests and they still pass?

**Comment by mpolci** [comment]
Yes, all ok.
```
Finished in 0.04 seconds
165 tests, 85 assertions, 0 failures, 0 skipped

(node) util.print is deprecated. Use console.log instead.

=============================================================================
Writing coverage object [/home/user/Desktop/javascript/Preconditions/coverage/coverage.json]
Writing coverage reports at [/home/user/Desktop/javascript/Preconditions/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 99.9% ( 1019/1020 )
Branches     : 99.29% ( 139/140 )
Functions    : 99.28% ( 411/414 )
Lines        : 99.89% ( 939/940 )
================================================================================
```

**Comment by mpolci** [comment]
I also checked the release note: https://github.com/lodash/lodash/wiki/Changelog#v300 

I doesn't notice anything used in Preconditions.

**Comment by corybill** [comment]
I will push out a new version sometime today.  Thanks mpolci!

**Comment by mpolci** [comment]
Thanks to you!

**Pull request merged**
